### PR TITLE
running SpecBind.CodedUI.IntegrationTests.dll tests

### PR DESCRIPTION
**Pull request by icnocop**

### CODE REVIEW

**Comment by dpiessens** [comment]
Is this complete? It looks like builds get blocked by the RDP command enable on init.

**Comment by icnocop** [comment]
No, this is not yet complete, sorry.

**Comment by icnocop** [comment]
This is now complete.

There are some integration tests that are failing with errors similar to the third bullet point described in https://github.com/dpiessens/specbind/issues/70.

I've also run into similar errors during my own integration testing when using SpecBind.

I may have resolved those issues in https://github.com/dpiessens/specbind/pull/151, but I'm not sure yet.

Here are the test results in the latest build from my fork (main branch): https://ci.appveyor.com/project/icnocop/specbind/build/1.7.3.29/tests

Thank you.

**Comment by icnocop** [comment]
I've confirmed that I've resolved these issues in #151 so this is superseded by it.

**Pull request closed without merging**
